### ISSUE TITLE
Documentation is confusing

### ISSUE THREAD

**Issue by stphnlyd** [Getty/p5-moox-cmd#8]
This module looks cool but I find its doc confusing. For example in SYNOPSIS, 

- Why is there both a `MyApp` and a `MyZapp`? What is the difference between them? 
- For the `MyZapp `package, what does that `execute_from_new => 0` mean? 
- And what is `command_args` in `MyZapp::Cmd::Command`? In the "MooX::Cmd Attributes" section a few of the attributes including `command_args` are "TODO"?

**Comment by rehsack** [comment]
Hi stphnlyd,

the SYNOPSIS is not intended to explain in detail all facettes of a module and it's infrastructure. The difference you ask to get explained result from Moo attributes and object creation. It is highly recommended to read the documentation of Moo and probably some of the slides of the one or other talk about Moo or Moose.

MooX::Cmd could need an improvement how to deal with the extra arguments in CLI - maybe not in MooX::Cmd but in a successor to allow pluggable option parsers and not hand-dangled marriage as happend with MooX::Options from Celogeek. For attribute documentation, please seriously read why you have to read https://metacpan.org/pod/MooX::Cmd::Role#command_args :)

Cheers,
Jens
